// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hiding': string;
  'showing': string;
  'subheading': string;
}
export const cssExports: CssExports;
export default cssExports;
