// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AnchorContainer': string;
  'AnnotationContainer': string;
  'AnnotationItem': string;
  'ContentContainer': string;
  'LocationContainer': string;
  'Pad': string;
  'cancel': string;
  'vscode-dark': string;
  'vscode-high-contrast': string;
  'vscode-light': string;
}
export const cssExports: CssExports;
export default cssExports;
