// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AnchorContainer': string;
  'AnnotationContainer': string;
  'AnnotationItem': string;
  'AnnotationOptionsTitle': string;
  'AnnotationsOptions': string;
  'ContentContainer': string;
  'DropdownIcons': string;
  'DropdownIconsWrapper': string;
  'DropdownItemOverwrite': string;
  'IconContainer': string;
  'LocationContainer': string;
  'Pad': string;
  'TitleContainer': string;
  'active': string;
  'btn-primary': string;
  'cancel': string;
  'container': string;
  'disabled': string;
  'dropdown': string;
  'dropdown-toggle': string;
  'profile': string;
  'row': string;
  'show': string;
  'submit': string;
  'vertical-center': string;
  'vscode-dark': string;
  'vscode-high-contrast': string;
  'vscode-light': string;
}
export const cssExports: CssExports;
export default cssExports;
