// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'align-items-center': string;
  'align-self-start': string;
  'border-1px-medium': string;
  'border-radius-8': string;
  'flex': string;
  'flex-col': string;
  'justify-content-center': string;
  'justify-content-space-between': string;
  'm2': string;
  'p1': string;
  'p2': string;
  'p4': string;
  'wh-80': string;
}
export const cssExports: CssExports;
export default cssExports;
