// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'border-1': string;
  'flex': string;
  'flex-col': string;
  'list-none': string;
  'm-4': string;
  'ml-2': string;
  'my-2': string;
  'pl-0': string;
  'text-center': string;
}
export const cssExports: CssExports;
export default cssExports;
