// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AuthContainer': string;
  'InputFieldContainer': string;
  'row': string;
  'welcome': string;
}
export const cssExports: CssExports;
export default cssExports;
