// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'align-center': string;
  'border-1px-medium': string;
  'border-radius-8': string;
  'flex': string;
  'flex-col': string;
  'font-14': string;
  'font-500': string;
  'font-size-medium': string;
  'justify-end': string;
  'mb4': string;
  'overflow-scroll': string;
  'p1': string;
  'p2': string;
  'p4': string;
}
export const cssExports: CssExports;
export default cssExports;
