// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AnchorCode': string;
  'AnchorCodeText': string;
  'AnchorCodeTextLight': string;
  'AnchorContainer': string;
  'AnchorWrapper': string;
  'CodeLines': string;
  'Merged': string;
  'MergedAnchorContainer': string;
  'ReanchorTitle': string;
  'Selected': string;
  'Suggestion': string;
  'SuggestionTitle': string;
  'Suggestions': string;
  'codeStyle': string;
  'disabled': string;
  'reanchor': string;
  'remove': string;
}
export const cssExports: CssExports;
export default cssExports;
