// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AnchorContainer': string;
  'reanchor': string;
  'remove': string;
}
export const cssExports: CssExports;
export default cssExports;
